# Generated by build-engine's dockerfile-resolver.js when a NEXT_SSR project
# has no Dockerfile of its own at its repo root. Two-stage build: `builder`
# runs the project's own INSTALL_COMMAND/BUILD_COMMAND (unchanged from the
# STATIC pipeline — see script.js), `runner` is what actually ships to
# Lambda. Keeping them separate is what keeps the final image small: dev
# dependencies, the .git history, and the full node_modules tree used only
# at build time never make it into the image AWS charges you to store and
# pull cold-start.
#
# Requires the target repo's next.config.js to set `output: 'standalone'`.
# Without it, `.next/standalone` doesn't exist and this build fails at the
# COPY step below with a clear "not found" error — see
# dockerfile-resolver.js's own check for this, which fails the build BEFORE
# Kaniko even starts, with a much more actionable error message than
# Docker's own COPY failure would give.
FROM node:22-slim AS builder
WORKDIR /app
COPY . .
RUN __INSTALL_COMMAND__
RUN __BUILD_COMMAND__

FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# The Lambda Web Adapter itself — a single static binary dropped into
# /opt/extensions, where Lambda's own container runtime auto-discovers and
# loads it as a Lambda Extension on cold start, BEFORE the app process
# below is started. This one line is the entire integration; nothing in
# the Next.js app itself needs to know it's running on Lambda. Works with
# this plain node:22-slim base image (not one of AWS's own Lambda base
# images) because the adapter ships its own Runtime Interface Client — see
# https://github.com/awslabs/aws-lambda-web-adapter.
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.0.1 /lambda-adapter /opt/extensions/lambda-adapter

# Next.js's `output: 'standalone'` build produces a self-contained
# node_modules subset under .next/standalone — copying just these three
# paths (not the builder's full /app) is what keeps the runtime image lean.
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
