#!/usr/bin/env bash
# Generates:
#   .env.deploy                 — read by docker-compose.prod.yml itself
#   apps/api-server/.env        — read by the api-server container
#   apps/reverse-proxy/.env     — read by the reverse-proxy container
#
# Idempotent by REFUSING to overwrite a file that already exists, rather
# than silently regenerating it — regenerating JWT_ACCESS_SECRET or
# ENCRYPTION_KEY on a second run would invalidate every existing login
# session and make every already-encrypted GitHub token in the database
# undecryptable. Re-running install.sh on an already-installed box should
# be safe; blowing away working secrets is the opposite of safe. Delete
# the specific .env file yourself first if you genuinely want it
# regenerated.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=./common.sh
source "${SCRIPT_DIR}/common.sh"

# Args: DOMAIN POSTGRES_PASSWORD (both required, passed in by install.sh
# rather than re-derived here, so there's exactly one source of truth for
# them across every generated file).
DOMAIN="${1:?generate-env.sh requires DOMAIN as \$1}"
POSTGRES_PASSWORD="${2:?generate-env.sh requires POSTGRES_PASSWORD as \$2}"

write_if_absent() {
  local path="$1"
  local content="$2"
  if [[ -f "${path}" ]]; then
    log_warn "${path} already exists — leaving it untouched (delete it yourself first if you want it regenerated)."
    return
  fi
  echo "${content}" > "${path}"
  chmod 600 "${path}"
  log_ok "Wrote ${path}"
}

generate_all_env_files() {
  local jwt_access jwt_refresh encryption_key

  jwt_access="$(random_hex 32)"     # >=32 CHARS required by env.ts — 32 bytes hex-encoded is 64 chars, comfortably over.
  jwt_refresh="$(random_hex 32)"
  encryption_key="$(random_hex 32)" # MUST be exactly 64 hex chars (32 bytes) — env.ts enforces this exactly; do not change the byte count.

  # --- .env.deploy — consumed by docker-compose.prod.yml's own
  # ${VARIABLE} interpolation (build args, the nginx container's DOMAIN,
  # Postgres's own startup credentials) — NOT read by any application
  # code directly.
  write_if_absent "${REPO_ROOT}/.env.deploy" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh — read by docker-compose.prod.yml
# itself (build args, container environment), not by application code.
DOMAIN=${DOMAIN}
POSTGRES_USER=dreamer
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=dreamer
NEXT_PUBLIC_API_BASE_URL=https://api.${DOMAIN}
NEXT_PUBLIC_SOCKET_URL=https://api.${DOMAIN}
EOF
)"

  # --- apps/api-server/.env
  #
  # DATABASE_URL / REDIS_URL point at the COMPOSE SERVICE NAMES
  # (postgres/redis), not localhost or a cloud provider — this is the
  # actual "no cloud Postgres/Redis needed" part: both run as containers
  # on this same box, reachable over the private docker compose network,
  # never exposed to the host or the internet at all (see
  # docker-compose.prod.yml — neither service publishes a host port).
  #
  # DATABASE_CA_CERT is required by env.ts's schema unconditionally, but
  # lib/prisma.ts only actually READS it outside of NODE_ENV=production
  # (production uses `rejectUnauthorized: false` instead, appropriate for
  # a same-host, unencrypted connection to a container on the private
  # compose network — there's no public network hop for a CA to protect
  # against here). The placeholder below exists purely to satisfy that
  # required-but-unused-in-production validation; it is never parsed as
  # an actual certificate.
  write_if_absent "${REPO_ROOT}/apps/api-server/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
# Lines marked TODO are placeholders — the installer cannot generate
# these for you (they require creating real accounts/apps of your own).
# The api-server container WILL crash-loop until you fill these in — see
# docs/SELF-HOSTING.md's "Finish the setup" section. That's expected, not
# a bug: env.ts fails fast on boot specifically so a misconfiguration
# shows up immediately in \`docker compose logs api-server\`, not three
# requests into production.

NODE_ENV=production
PORT=8000
FRONTEND_URL=https://${DOMAIN}

DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
DATABASE_CA_CERT=not-used-in-production-see-lib-prisma-ts
REDIS_URL=redis://redis:6379

JWT_ACCESS_SECRET=${jwt_access}
JWT_REFRESH_SECRET=${jwt_refresh}
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=7

ENCRYPTION_KEY=${encryption_key}

# TODO — create a GitHub OAuth App at https://github.com/settings/developers
#   Homepage URL:             https://${DOMAIN}
#   Authorization callback URL: https://api.${DOMAIN}/api/auth/github/callback
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_CALLBACK_URL=https://api.${DOMAIN}/api/auth/github/callback

# TODO — only needed once you actually deploy apps (this is unrelated to
# hosting the Dreamer PLATFORM on this VPS — deployed user apps still run
# on AWS ECS/Lambda regardless of where this control plane runs). See
# docs/AWS-Console-Setup-Guide.md for what each of these needs to be.
AWS_REGION=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET=
TASK_DEFINITION_IMAGE_NAME=build-image
ECS_CLUSTER_ARN=
ECS_TASK_DEFINITION_ARN=
ECS_SUBNET1_ARN=
ECS_SUBNET2_ARN=
ECS_SUBNET3_ARN=
ECS_SECURITY_GROUP_ARN=
ECR_REPOSITORY_URI=
LAMBDA_EXECUTION_ROLE_ARN=
LAMBDA_ARCHITECTURE=x86_64
EOF
)"

  # --- apps/reverse-proxy/.env
  #
  # Same local Postgres/Redis wiring as api-server's .env above — this is
  # the file that used to have ZERO database dependency before DYNAMIC
  # support existed; it now needs real connection info, and for a
  # self-hosted install that's the SAME local containers, not a second
  # separate database.
  write_if_absent "${REPO_ROOT}/apps/reverse-proxy/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
BASE_DOMAIN=${DOMAIN}
DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
REDIS_URL=redis://redis:6379
EOF
)"
}

generate_all_env_files
