#!/usr/bin/env bash
# Generates:
#   .env.deploy          — read by docker-compose.yml's own interpolation
#   api-server/.env       — read by the api-server + build-worker containers
#   reverse-proxy/.env    — read by the reverse-proxy container
#
# Idempotent by REFUSING to overwrite a file that already exists — same
# reasoning as the repo root's own scripts/lib/generate-env.sh: regenerating
# JWT_ACCESS_SECRET or ENCRYPTION_KEY on a second run invalidates every
# existing session and makes every already-encrypted GitHub token
# undecryptable. Delete the specific file yourself first if you genuinely
# want it regenerated.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_ENGINE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=./common.sh
source "${SCRIPT_DIR}/common.sh"

# Args: DOMAIN POSTGRES_PASSWORD MINIO_ROOT_PASSWORD (all required, passed
# in by install.sh — one source of truth for each across every generated
# file, same as the repo root's own generate-env.sh).
DOMAIN="${1:?generate-env.sh requires DOMAIN as \$1}"
POSTGRES_PASSWORD="${2:?generate-env.sh requires POSTGRES_PASSWORD as \$2}"
MINIO_ROOT_PASSWORD="${3:?generate-env.sh requires MINIO_ROOT_PASSWORD as \$3}"

write_if_absent() {
  local path="$1"
  local content="$2"
  if [[ -f "${path}" ]]; then
    log_warn "${path} already exists — leaving it untouched (delete it yourself first if you want it regenerated)."
    return
  fi
  echo "${content}" > "${path}"
  chmod 600 "${path}"
  if [[ "${EUID}" -eq 0 && -n "${SUDO_USER:-}" ]]; then
    chown "${SUDO_USER}:$(id -gn "${SUDO_USER}")" "${path}" || true
  fi
  log_ok "Wrote ${path}"
}

generate_all_env_files() {
  local jwt_access jwt_refresh encryption_key

  jwt_access="$(random_hex 32)"
  jwt_refresh="$(random_hex 32)"
  encryption_key="$(random_hex 32)"

  # --- .env.deploy ---------------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/.env.deploy" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh — read by docker-compose.yml
# itself (build args, container environment), not by application code.
DOMAIN=${DOMAIN}
POSTGRES_USER=dreamer
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=dreamer
MINIO_ROOT_USER=dreamer
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
S3_BUCKET=dreamer-outputs
# Dashboard is loopback-only (Decision 4) — the browser that loads this
# frontend build is always on the operator's OWN machine, reached via an
# SSH tunnel to 127.0.0.1, so these point at localhost regardless of
# ${DOMAIN}. There is no api.${DOMAIN} anymore; nginx never routes one.
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
NEXT_PUBLIC_SOCKET_URL=http://localhost:8000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
ENABLE_PUSH_DEPLOY=false
BUILD_WORKER_CONCURRENCY=5
EOF
)"

  # --- api-server/.env -------------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/api-server/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
# Lines marked TODO are placeholders this script cannot generate for you
# api-server WILL crash-loop until you set a git Personal Access Token
# from Settings after first login (Decision 2) if you want to deploy
# private repos — that's a runtime, in-app step now, not an env var here.

NODE_ENV=production
PORT=8000
# Loopback-only by design — see
# docs/architecture/local-engine-auth-and-networking.md Decision 4. The
# dashboard is reached over an SSH tunnel to 127.0.0.1:3000, never a public
# hostname, so FRONTEND_URL stays localhost even in production.
FRONTEND_URL=http://localhost:3000

DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
DATABASE_CA_CERT=not-used-in-production-see-lib-prisma-ts
REDIS_URL=redis://redis:6379
REDIS_BUILDER_URL=redis://redis-builder:6379

DOCKER_BUILD_ENGINE_IMAGE=dreamer-build-engine:local
DOCKER_NETWORK=dreamer-local

AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=dreamer
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
S3_ENDPOINT_URL=http://minio:9000
S3_FORCE_PATH_STYLE=true
S3_BUCKET=dreamer-outputs

JWT_ACCESS_SECRET=${jwt_access}
JWT_REFRESH_SECRET=${jwt_refresh}
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=7
ENCRYPTION_KEY=${encryption_key}

# Push-to-deploy webhook — OFF by default (Decision 3 & 4). Leave commented
# out unless you want \`git push\` to trigger a deploy automatically; manual
# "Redeploy" from the dashboard always works either way.
# GITHUB_WEBHOOK_SECRET=
# ENABLE_PUSH_DEPLOY=false
# API_PUBLIC_URL=https://hooks.${DOMAIN}

BASE_DOMAIN=${DOMAIN}
EOF
)"

  # --- reverse-proxy/.env -----------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/reverse-proxy/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
BASE_DOMAIN=${DOMAIN}
BASE_PATH=http://minio:9000/dreamer-outputs/__outputs
DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
REDIS_URL=redis://redis:6379
EOF
)"
}

generate_all_env_files
