import { spawn, spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs'
import { platform } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
// cli/src/lib.js -> local-engine root is two levels up.
export const ROOT = join(__dirname, '..', '..')
const COMPOSE_FILE = 'docker-compose.local.yml'
const ENV_FILE = '.env.local'

const c = {
  blue: (s) => `\x1b[34m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
}
export const log = {
  step: (m) => console.log(`${c.blue('==>')} ${m}`),
  ok: (m) => console.log(`${c.green('✓')} ${m}`),
  warn: (m) => console.log(`${c.yellow('!')} ${m}`),
  error: (m) => console.error(`${c.red('✗')} ${m}`),
}

export function fatal(msg) {
  log.error(msg)
  process.exit(1)
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', cwd: ROOT, ...opts })
  return result.status === 0
}

function runStreaming(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { stdio: 'inherit', cwd: ROOT, ...opts })
    child.on('exit', (code) => resolve(code === 0))
    child.on('error', () => resolve(false))
  })
}

function dockerComposeArgs(...rest) {
  return ['compose', '-f', COMPOSE_FILE, '--env-file', ENV_FILE, ...rest]
}

// Docker / Compose availability

const INSTALL_DOCKER_URL = {
  darwin: 'https://docs.docker.com/desktop/setup/install/mac-install/',
  win32: 'https://docs.docker.com/desktop/setup/install/windows-install/',
  linux: 'https://docs.docker.com/engine/install/',
}

export function checkDocker() {
  const os = platform()
  const hasCli = spawnSync('docker', ['--version'], { stdio: 'ignore' }).status === 0
  if (!hasCli) {
    log.error('Docker was not found on your PATH.')
    log.warn(
      os === 'linux'
        ? 'Install Docker Engine, then re-run this command:'
        : 'Install Docker Desktop, then re-run this command:'
    )
    console.log(`  ${INSTALL_DOCKER_URL[os] ?? INSTALL_DOCKER_URL.linux}`)
    return false
  }

  const daemonUp = spawnSync('docker', ['info'], { stdio: 'ignore' }).status === 0
  if (!daemonUp) {
    log.error('Docker is installed but the daemon isn\'t running.')
    log.warn(
      os === 'linux'
        ? 'Start it with: sudo systemctl start docker'
        : 'Open Docker Desktop and wait for it to finish starting, then re-run this command.'
    )
    return false
  }

  const composeOk = spawnSync('docker', ['compose', 'version'], { stdio: 'ignore' }).status === 0
  if (!composeOk) {
    log.error('The `docker compose` plugin (v2) was not found.')
    log.warn('Docker Desktop bundles this automatically. On Linux, see the Compose plugin install docs.')
    return false
  }

  log.ok('Docker is installed and running.')
  return true
}

// --- Env generation (Node equivalent of scripts/lib/generate-env.sh) --

function randomHex(bytes) {
  return randomBytes(bytes).toString('hex')
}

function writeIfAbsent(path, content) {
  if (existsSync(path)) {
    log.warn(`${path} already exists — leaving it untouched (delete it yourself first if you want it regenerated).`)
    return
  }
  writeFileSync(path, content)
  if (platform() !== 'win32') {
    try {
      chmodSync(path, 0o600)
    } catch {
      // best-effort, same as the bash script's `|| true` on chown
    }
  }
  log.ok(`Wrote ${path}`)
}

export function generateEnvFiles({ domain = 'localtest.me' } = {}) {
  log.step('Generating secrets and .env files')

  const postgresPassword = randomHex(24)
  const minioRootPassword = randomHex(24)
  const jwtAccess = randomHex(32)
  const jwtRefresh = randomHex(32)
  const encryptionKey = randomHex(32)

  writeIfAbsent(
    join(ROOT, ENV_FILE),
    `# Generated by dreamer-local — read by docker-compose.local.yml.
DOMAIN=${domain}
POSTGRES_USER=dreamer
POSTGRES_PASSWORD=${postgresPassword}
POSTGRES_DB=dreamer
MINIO_ROOT_USER=dreamer
MINIO_ROOT_PASSWORD=${minioRootPassword}
S3_BUCKET=dreamer-outputs
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
NEXT_PUBLIC_SOCKET_URL=http://localhost:8000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
BUILD_WORKER_CONCURRENCY=5
FRONTEND_PORT=3000
API_PORT=8000
REVERSE_PROXY_PORT=8080
`
  )

  writeIfAbsent(
    join(ROOT, 'api-server', '.env'),
    `# Generated by dreamer-local.
NODE_ENV=production
PORT=8000
FRONTEND_URL=http://localhost:3000

DATABASE_URL=postgresql://dreamer:${postgresPassword}@postgres:5432/dreamer
REDIS_URL=redis://redis:6379
REDIS_BUILDER_URL=redis://redis-builder:6379

DOCKER_BUILD_ENGINE_IMAGE=dreamer-build-engine:local
DOCKER_NETWORK=dreamer-local

AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=dreamer
AWS_SECRET_ACCESS_KEY=${minioRootPassword}
S3_ENDPOINT_URL=http://minio:9000
S3_FORCE_PATH_STYLE=true
S3_BUCKET=dreamer-outputs

JWT_ACCESS_SECRET=${jwtAccess}
JWT_REFRESH_SECRET=${jwtRefresh}
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=7
ENCRYPTION_KEY=${encryptionKey}

BASE_DOMAIN=${domain}
`
  )

  writeIfAbsent(
    join(ROOT, 'reverse-proxy', '.env'),
    `# Generated by dreamer-local.
BASE_DOMAIN=${domain}
BASE_PATH=http://minio:9000/dreamer-outputs/__outputs
DATABASE_URL=postgresql://dreamer:${postgresPassword}@postgres:5432/dreamer
REDIS_URL=redis://redis:6379
`
  )
}

function readEnvVar(path, key) {
  if (!existsSync(path)) return undefined
  const line = readFileSync(path, 'utf8')
    .split('\n')
    .find((l) => l.startsWith(`${key}=`))
  return line ? line.slice(key.length + 1).trim() : undefined
}

// --- Build / up / migrate / down --------------------------------------

export async function buildBuildEngineImage() {
  log.step('Building the build-engine image')
  const ok = await runStreaming('docker', ['build', '-t', 'dreamer-build-engine:local', 'build-engine'])
  if (!ok) fatal('Failed to build the build-engine image.')
  log.ok('build-engine image ready')
}

export async function composeUp() {
  log.step('Building and starting the stack (first run can take a few minutes)')
  const ok = await runStreaming('docker', dockerComposeArgs('up', '-d', '--build'))
  if (!ok) fatal('docker compose up failed — see the output above.')
  log.ok('Stack is up')
}

export async function runMigrations() {
  log.step('Running database migrations')
  for (let attempt = 1; attempt <= 5; attempt++) {
    const ok = await runStreaming(
      'docker',
      dockerComposeArgs('run', '--rm', '--entrypoint', 'sh', 'api-server', '-c', 'npx prisma migrate deploy')
    )
    if (ok) {
      log.ok('Migrations applied')
      return
    }
    if (attempt === 5) fatal('Migrations failed after 5 attempts — check `dreamer-local logs postgres`.')
    log.warn(`Migration attempt ${attempt} failed (Postgres may still be starting) — retrying in 5s...`)
    await new Promise((r) => setTimeout(r, 5000))
  }
}

export async function composeDown(removeVolumes) {
  log.step(removeVolumes ? 'Stopping the stack and removing volumes' : 'Stopping the stack')
  const args = removeVolumes ? ['down', '-v'] : ['down']
  await runStreaming('docker', dockerComposeArgs(...args))
}

export async function composeLogs(service) {
  const args = service ? ['logs', '-f', service] : ['logs', '-f']
  await runStreaming('docker', dockerComposeArgs(...args))
}

export async function composePs() {
  await runStreaming('docker', dockerComposeArgs('ps'))
}

export function printSummary() {
  const domain = readEnvVar(join(ROOT, ENV_FILE), 'DOMAIN') || 'localtest.me'
  const proxyPort = readEnvVar(join(ROOT, ENV_FILE), 'REVERSE_PROXY_PORT') || '8080'
  console.log('')
  log.ok('Dreamer Local Engine is running.')
  console.log('')
  log.step('Dashboard:  http://localhost:3000  (first load is the one-time admin setup screen)')
  log.step('API:        http://localhost:8000')
  log.step(`Deployed apps will be reachable at: http://<project-slug>.${domain}:${proxyPort}`)
  console.log('')
  log.warn(`"${domain}" and all its subdomains already resolve to 127.0.0.1 — no DNS or /etc/hosts changes needed.`)
  console.log('')
  console.log('Useful commands:')
  console.log('  dreamer-local logs [service]   tail logs')
  console.log('  dreamer-local ps               container status')
  console.log('  dreamer-local down             stop the stack')
  console.log('  dreamer-local down --volumes   stop and wipe all data')
}
